
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logusername = new javax.swing.JTextField();
        logpassword = new javax.swing.JPasswordField();
        logshowpassword = new javax.swing.JCheckBox();
        logexit = new javax.swing.JButton();
        loglogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 109, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 109, 32));

        logusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(logusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 390, 210, 30));

        logpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(logpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 440, 208, 30));

        logshowpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logshowpassword.setText("Show Password");
        logshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logshowpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(logshowpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 500, -1, -1));

        logexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        logexit.setText("Close");
        logexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logexitActionPerformed(evt);
            }
        });
        getContentPane().add(logexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 560, 100, -1));

        loglogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loglogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        loglogin.setText("Login");
        loglogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logloginActionPerformed(evt);
            }
        });
        getContentPane().add(loglogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 560, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login ani.gif"))); // NOI18N
        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 260, 255, 85));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login background.PNG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1440, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logexitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close Application", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a==0){
            System.exit(0);
        }
        
    }//GEN-LAST:event_logexitActionPerformed

    private void logloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logloginActionPerformed
        // TODO add your handling code here:
        
        if(logusername.getText().equals("Rajib") && logpassword.getText().equals("admin"))
        {
            
            setVisible(false);
            new Home().setVisible(true);
        }
        else{JOptionPane.showMessageDialog(null,"Incorrect Username or Password");
        
        }
    }//GEN-LAST:event_logloginActionPerformed

    private void logshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logshowpasswordActionPerformed
        // TODO add your handling code here:
        
        if(logshowpassword.isSelected())
        {
            logpassword.setEchoChar((char)0);
            
        }
        else{
            logpassword.setEchoChar('*');
        }
            
    }//GEN-LAST:event_logshowpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logexit;
    private javax.swing.JButton loglogin;
    private javax.swing.JPasswordField logpassword;
    private javax.swing.JCheckBox logshowpassword;
    private javax.swing.JTextField logusername;
    // End of variables declaration//GEN-END:variables
}
